import { NextResponse } from "next/server";
import { getPuzzle } from "@/lib/puzzle-service";
import type { Mode } from "@/lib/generate";

// The Anthropic SDK needs the Node runtime (not edge). Pinning to one region
// makes the daily Data Cache entry far less likely to be regenerated by a
// cold cache in a second region.
export const runtime = "nodejs";
export const preferredRegion = "iad1";
export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const mode: Mode =
    new URL(request.url).searchParams.get("mode") === "daily"
      ? "daily"
      : "endless";
  return NextResponse.json({ mode, ...(await getPuzzle(mode)) });
}
